# Generated by Django 5.1.1 on 2024-10-03 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=64, null=True)),
                ('originIataCode', models.CharField(blank=True, max_length=6, null=True)),
                ('destination', models.CharField(blank=True, max_length=64, null=True)),
                ('destinationIataCode', models.CharField(blank=True, max_length=6, null=True)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('one_way', models.BooleanField(default=False)),
                ('return_flight', models.BooleanField(default=False)),
                ('airline', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('num_tickets', models.IntegerField(null=True)),
                ('passenger_names', models.CharField(max_length=255, null=True)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('payment_status', models.CharField(max_length=32, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=64, null=True)),
                ('originIataCode', models.CharField(blank=True, max_length=6, null=True)),
                ('destination', models.CharField(blank=True, max_length=64, null=True)),
                ('destinationIataCode', models.CharField(blank=True, max_length=6, null=True)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('one_way', models.BooleanField(default=False, null=True)),
                ('return_flight', models.BooleanField(default=False, null=True)),
                ('airline', models.CharField(blank=True, max_length=64, null=True)),
                ('trip_purpose', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('travel_class', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
