# Generated by Django 4.2.15 on 2024-08-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_searchquery_flight_airline_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='query',
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='num_passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
