# Generated by Django 4.2.15 on 2024-09-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_booking_flight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='travel_class',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
