# Generated by Django 5.1.1 on 2024-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_searchquery_travel_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destinationIataCode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='originIataCode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='destinationIataCode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='originIataCode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='one_way',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='return_flight',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
