# Generated by Django 5.1.1 on 2024-10-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('individual', 'Individual'), ('org_consumer', 'Organization'), ('org_provider', 'Service Provider')], max_length=20),
        ),
    ]
